### ISSUE TITLE
undefined: fem.DofU

### ISSUE THREAD

**Issue by FieldsYeh** [soypat/go-fem#2]
go1.18 build .

.\example.go:26:41: undefined: fem.DofU
.\example.go:27:12: ga.AddIsoparametric3s undefined (type *fem.GeneralAssembler has no field or method AddIsoparametric3s)

[example](https://github.com/soypat/go-fem#example) from README  
example.go 
package main

import (
	"fmt"

	"github.com/soypat/go-fem"
	"github.com/soypat/go-fem/elements"
	"gonum.org/v1/gonum/mat"
	"gonum.org/v1/gonum/spatial/r3"
)

// Calculates the stiffness matrix of a single isoparametric tetrahedron element.
// and prints the result.
func main() {
	elemType := elements.Tetra4{}
	steel := fem.IsotropicMaterial{E: 200e9, Poisson: 0.3}
	nod := []r3.Vec{
		{X: 0, Y: 0, Z: 0},
		{X: 1}, // is (1,0,0) point
		{Y: 1},
		{Z: 1},
	}
	elems := [][]int{
		{0, 1, 2, 3}, // one single element.
	}
	ga := fem.NewGeneralAssembler(nod, fem.DofU)
	err := ga.AddIsoparametric3s(elemType, steel, len(elems), func(i int) []int {
		return elems[i]
	})
	if err != nil {
		panic(err)
	}
	fmt.Printf("K=\n%.5g", mat.Formatted(ga.Ksolid()))
}

**Comment by soypat** [comment]
Thank you for submitting the issue! I've fixed it in the latest commit [ceac2bb](https://github.com/soypat/go-fem/commit/ceac2bbec9c13bfa719e22a4837510d39aaedae6)
